### ISSUE TITLE
can't use flownet2

### ISSUE THREAD

**Issue by bobbyhanbin** [Archer-Tatsu/V-CNN#2]
Traceback (most recent call last):
  File "/dev/360/flownet2/models.py", line 9, in <module>
    from networks.resample2d_package.resample2d import Resample2d
ImportError: No module named 'networks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    from flownet2.models import FlowNet2
  File "/dev/360/flownet2/models.py", line 19, in <module>
    from .networks.resample2d_package.resample2d import Resample2d
  File "/dev/360/flownet2/networks/resample2d_package/resample2d.py", line 3, in <module>
    import resample2d_cuda
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

how to solve this?

**Comment by Archer-Tatsu** [comment]
It seems that these errors are due to the FlowNet2 module. Please follow the instructions of FlowNet2 to install and use this module.
